# Generated by Django 4.2.11 on 2024-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('release', models.IntegerField()),
            ],
        ),
    ]
