# Generated by Django 4.2.11 on 2024-03-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
